# название workflow (имя даём сами):
name: Webpack CI/CD

# способы запуска workflow:
on:
  # 1. при каждом пуше в ветку 'main'
  push:
    branches: 
      - main
    paths-ignore:
      - '**/*.md'
      - 'LICENSE'
  # 2. разрешаем также ручной запуск из вкладки Actions на GitHub
  workflow_dispatch:

# настройка разрешений для токена GITHUB_TOKEN для деплоя на GitHub Pages:
permissions:
  contents: read   # разрешить чтение содержимого
  pages: write     # разрешить запись на GitHub Pages
  id-token: write  # разрешить использование токена идентификации (для Pages)

# ограничение параллельных запусков workflow
concurrency:
  group: 'webpack-pages' # группа workflow для деплоя (имя даём сами)
  cancel-in-progress: true # отменяем старые, оставляем только последний запуск (актуальный деплой)

# описание работ:
jobs:
  # Job-1 - проверка кода линтером:
  lint:
    runs-on: windows-latest # работа будет выполнена на последней версии Ubuntu
    steps: # шаги выполнения работы
      # 1. клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v4
      # 2. установка Node.js и кеширование npm
      - name: Setup Node.js and enable yarn cache
        uses: actions/setup-node@v4
        with:
          node-version: 25.9.0
          cache: 'yarn'
      # 3. установка зависимостей
      - name: Install dependencies
        run: yarn install
      # 4. запуск линтера
      #- name: Run ESLint
       # run: npm run lint

  # Job-2 - сборка и деплой на GitHub Pages:
  build:
    # выполняется только после успешных работы 'lint'
    #needs: 
    #  - lint
    runs-on: windows-latest # работа будет выполнена на последней версии Ubuntu
    environment: # настройки окружения для развёртывания на GitHub Pages
      name: github-pages # имя окружения
      url: ${{ steps.deployment.outputs.page_url }} # URL для деплоя (вывод из шага deployment)

    steps: # шаги выполнения работы
      # 1. клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v4
      # 2. установка Node.js и кеширование yarn
      - name: Setup Node.js and enable npm cache
        uses: actions/setup-node@v4
        with:
          node-version: 20.13.1
          cache: 'yarn'
      # 3. установка зависимостей
      - name: Install dependencies
        run: yarn install
      # 4. очистка старых артефактов Pages (по необходимости)
      - name: Clean old build artifacts
        run: rm -rf ./dist || true
      # 5. сборка проекта
      - name: Build project
        run: yarn build
      # 6. настройка Pages и environment:
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v4
      # 7. загрузка новых артефактов (dist) для деплоя:
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist' # указываем директорию с готовой сборкой
      # 8. деплой на GitHub Pages:
      - name: Deploy to GitHub Pages
        id: deployment # deployment позволяет получить URL страницы через outputs
        uses: actions/deploy-pages@v4
